In [2]:
import numpy as np
A=np.array([[1,2],[3,4]])
A.dot(A)

array([[ 7, 10],
       [15, 22]])

In [3]:
A=np.zeros([3,3])
A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.empty([2,2])

array([[1.69119330e-306, 1.78022342e-306],
       [4.22801381e-307, 2.04722549e-306]])

In [6]:
np.full([3,4],9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [8]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [10]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [12]:
np.linspace(10,40,8)

array([10.        , 14.28571429, 18.57142857, 22.85714286, 27.14285714,
       31.42857143, 35.71428571, 40.        ])

In [16]:
np.logspace(2,5,3)

array([   100.        ,   3162.27766017, 100000.        ])

In [17]:
np.diag([4,5,6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [18]:
np.tri(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
B=np.vander([4,5,6,7,9])

In [39]:
B.shape

(5, 5)

In [40]:
B.T

array([[ 256,  625, 1296, 2401, 6561],
       [  64,  125,  216,  343,  729],
       [  16,   25,   36,   49,   81],
       [   4,    5,    6,    7,    9],
       [   1,    1,    1,    1,    1]])

In [41]:
B.real

array([[ 256,   64,   16,    4,    1],
       [ 625,  125,   25,    5,    1],
       [1296,  216,   36,    6,    1],
       [2401,  343,   49,    7,    1],
       [6561,  729,   81,    9,    1]])

In [42]:
B.imag

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [43]:
C=B.copy()
C[0,0]=100
C

array([[ 100,   64,   16,    4,    1],
       [ 625,  125,   25,    5,    1],
       [1296,  216,   36,    6,    1],
       [2401,  343,   49,    7,    1],
       [6561,  729,   81,    9,    1]])

In [44]:
B

array([[ 256,   64,   16,    4,    1],
       [ 625,  125,   25,    5,    1],
       [1296,  216,   36,    6,    1],
       [2401,  343,   49,    7,    1],
       [6561,  729,   81,    9,    1]])

In [36]:
D=B.reshape(1,25)
D

array([[ 256,   64,   16,    4,    1,  625,  125,   25,    5,    1, 1296,
         216,   36,    6,    1, 2401,  343,   49,    7,    1, 6561,  729,
          81,    9,    1]])

In [45]:
B

array([[ 256,   64,   16,    4,    1],
       [ 625,  125,   25,    5,    1],
       [1296,  216,   36,    6,    1],
       [2401,  343,   49,    7,    1],
       [6561,  729,   81,    9,    1]])

In [46]:
B.resize(1,25)
B

array([[ 256,   64,   16,    4,    1,  625,  125,   25,    5,    1, 1296,
         216,   36,    6,    1, 2401,  343,   49,    7,    1, 6561,  729,
          81,    9,    1]])

In [47]:
np.eye(3).flatten()

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [48]:
B.max()

6561

In [49]:
A=np.vander([3,5,7,9])
A

array([[ 27,   9,   3,   1],
       [125,  25,   5,   1],
       [343,  49,   7,   1],
       [729,  81,   9,   1]])

In [51]:
# 左闭右开
A[1:4,1:3]

array([[25,  5],
       [49,  7],
       [81,  9]])

In [55]:
A[[1,2],[0,2]]

array([125,   7])

In [56]:
A[np.ix_([1,2],[0,2])]

array([[125,   5],
       [343,   7]])

In [57]:
for i in np.nditer(A):
    print(i)

27
9
3
1
125
25
5
1
343
49
7
1
729
81
9
1


In [60]:
np.vstack([np.vander([1,2,3]),np.vander([2,3,4])])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [61]:
np.hstack([np.vander([1,2,3]),np.vander([2,3,4])])

array([[ 1,  1,  1,  4,  2,  1],
       [ 4,  2,  1,  9,  3,  1],
       [ 9,  3,  1, 16,  4,  1]])

In [66]:
tensor=np.stack([np.vander([1,2,3]),np.vander([2,3,4])])
tensor

array([[[ 1,  1,  1],
        [ 4,  2,  1],
        [ 9,  3,  1]],

       [[ 4,  2,  1],
        [ 9,  3,  1],
        [16,  4,  1]]])

In [67]:
tensor.shape

(2, 3, 3)

In [68]:
np.sin(A)

array([[ 0.95637593,  0.41211849,  0.14112001,  0.84147098],
       [-0.61604046, -0.13235175, -0.95892427,  0.84147098],
       [-0.53659836, -0.95375265,  0.6569866 ,  0.84147098],
       [ 0.14993682, -0.62988799,  0.41211849,  0.84147098]])

In [69]:
np.tan(A)

array([[-3.2737038 , -0.45231566, -0.14254654,  1.55740772],
       [-0.78206057, -0.13352641, -3.38051501,  1.55740772],
       [ 0.63590226, -3.17290855,  0.87144798,  1.55740772],
       [ 0.15165115, -0.81099442, -0.45231566,  1.55740772]])

In [71]:
import numpy.ma as ma
x = np.array([1, 2, 3, -1, 5])
mx = ma.masked_array(x, mask=[0, 0, 0, 1, 0])
mx

masked_array(data=[1, 2, 3, --, 5],
             mask=[False, False, False,  True, False],
       fill_value=999999)

In [72]:
mx.mean()

2.75

In [74]:
mx = ma.masked_array(x, mask=[1, 0, 1, 1, 0])
# 仅对2和5求平均
mx.mean()

3.5